### ISSUE TITLE
Improve README/doc

### ISSUE THREAD

**Issue by marinang** [scikit-hep/numpythia#12]
By looking again a the code at I found out that most of the things I was looking for (in #2 for instance) but it is not documented.
You can for instance do a full a generator level study with numpythia which I thought was not possible.
Things that would be nice to show are:

- more general way to use events without using hepmc_write, hepmc_read, just with ```pythia(events=nevts)```
- Then says something about GenEvent and GenParticle and their attributes (numpythia interface to HepMC GenEvent. and GenParticle)
- Write all possible filters 

Also an example section can be added.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/numpythia/pull/14.
