### ISSUE TITLE
Parents/Children ID Filters

### ISSUE THREAD

**Issue by marinang** [scikit-hep/numpythia#2]
Hi.
I would be nice to have filters to select particles with a specific mother ID or with specific children IDs.

Also when I do event.all(), it returns a numpy ndarray but it would be nice to have either more dtypes (like eta, ancestors_id, children_id ...) or if we do event.all()[i] we get a GenParticle.

What I basically need to do, is to select decay particles from a specific mother and check and they pass an acceptance cut and then write the events passing into an HepMC ascii file.

Matt

**Comment by eduardo-rodrigues** [comment]
Hi Matt, did you follow-up on this on your own or with @ndawe? Is anyone working on this matter? Maybe @cvazquezs would be interested in working with you on this enhancement?

**Comment by marinang** [comment]
@eduardo-rodrigues I have a fork of numpythia with this working at least for new observables like eta, phi etc ... 
About particles ancestors/childs I haven't thought of anything.

**Comment by eduardo-rodrigues** [comment]
No pressure here, @marinang, but if your enhancements are ready to be committed for the common good, feel free to create a PR at some point … when you have time, of course :-).

**Comment by marinang** [comment]
@eduardo-rodrigues  I tried to rework on this but I cannot install it anymore anywhere, even with pip install numpythia ...

**Comment by eduardo-rodrigues** [comment]
Damn :-(. You mean the latest release? True that we made quite some updates in the releases 1.0.x, see https://github.com/scikit-hep/numpythia/releases. I suspect you are trying the latest … What kind of trouble do you get?

**Comment by marinang** [comment]
@eduardo-rodrigues never mind apparently it's working now 🤷‍♂️. It was compilation failures...

Ok now I can at least add the new observables (eta,  theta and phi). Others?
In order to get ancestor and children informations I need add a column about particle number in the event, and add columns ancestors/children (mothers/daughters) which are list/array containing the particle number of the mothers/childrens such as in a standard Pythia event record.
<img width="931" alt="capture d ecran 2019-02-18 a 16 33 32" src="https://user-images.githubusercontent.com/24250309/52961312-f03cb000-339a-11e9-89db-460507e4700f.png">

**Comment by eduardo-rodrigues** [comment]
Interesting! And I gave it a try on CERN's SWAN and upon installation as "--user" get the following trouble:
```
>>> pythia = Pythia(get_cmnd('w'), random_state=1)
 PYTHIA Abort from Pythia::Pythia: unmatched version numbers : in code 8.226 but in XML 8.235
 PYTHIA Abort from Pythia::init: constructor initialization failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpythia/src/_libnumpythia.pyx", line 380, in _libnumpythia._Pythia.__cinit__
RuntimeError: PYTHIA did not successfully initialize
```
This is confusing as I cloned the repo and cannot find anywhere the "235".  On the other hand, version 8.235 is installed on SWAN:
```
bash-4.2$ env | grep -i pythia
PYTHIA8=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/235-92c0a/x86_64-centos7-gcc7-opt
PYTHIA8DATA=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/235-92c0a/x86_64-centos7-gcc7-opt/share/Pythia8/xmldoc
```
Something fishy is going on, since numpythia uses its own version of Pythia and should not be communicating with whatever is installed ...


Good that you can proceed, though! Yes, eta, phi and theta are the obvious candidates. Maybe rapidity (y) itself, as some may use it instead of pseudorapidity (eta)?

**Comment by eduardo-rodrigues** [comment]
I'm cc'ing @henryiii in case he has an idea as to why there seems to be some interference going on ...

**Comment by marinang** [comment]
Oh I got that on my laptop as well, it's because I have pythia8 on installed so I had to remove environment variables such as PYTHIA8, PYTHIA8DATA, PYTHIAPATH, LD_LIBRARY_PATH=$HOME/pythia8230/lib:$LD_LIBRARY_PATH

**Comment by eduardo-rodrigues** [comment]
Hmm, I was not expecting such behaviour since `numpythia` ships its own Pythia. @ndawe, is this behaviour expected? It would then make sense to warn users in the README.

**Comment by henryiii** [comment]
If a user is manually setting LD_LIBRARY_PATH and PYTHONPATH, that breaks things. That’s why they should not be set, and packages should instead play nice. Some packages (like ROOT) don’t do to well with that yet.

**Comment by henryiii** [comment]
We might be able to do better, I’ll check on Wednesday, but setting things those paths is supposed to override normal lookups, it’s what they are for. Which tends to break things.
