### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by AlexSchuy** [scikit-hep/numpythia#21]
After encountering #20, I started exploring the code to see if it was feasible for me to submit a PR that fixes the issue. Related to that, it would be nice if there were a 'contribute' section in the README or elsewhere that gave a short guide on how to get started contributing to the project. 

A few paragraphs containing (1) how to setup the necessary tools, (2) how the code is structured, and (3) a link to a Cython reference or guide might help encourage contributions from new authors.

**Comment by eduardo-rodrigues** [comment]
That's a fair point. Finding a Cython reference is easy - https://cython.org/ - but providing some instructions to get started would help, sure. I know that both @marinang and @henryiii know Cython and have developped with it. Maybe they are ideal candidates to help with a little dev paragraph? (Sorry guys for suggesting extra work for you!)

**Comment by eduardo-rodrigues** [comment]
Closing at this stage since the package is unmaintained (aside minor updates from org admins) and effectively deprecated.
