### ISSUE TITLE
Add support for Pythia 8.244 and 8.303

### ISSUE THREAD

**Issue by okitouni** [scikit-hep/numpythia#25]
Would it be possible to update the Pythia version to 8.303?

**Comment by eduardo-rodrigues** [comment]
Thank you for the interest and for getting in touch. I was thinking about updates last week as well hence modified the title as I think we should try and have a release with the latest Pythia 8.2 series as well.

We are having trouble finding a proper maintainer for this package - a shame. Would you be willing to give this update a try, by any chance?

**Comment by eduardo-rodrigues** [comment]
@okitouni, I'm waiting for your response ...

**Comment by okitouni** [comment]
Newer versions of Pythia come with python bindings so I ended up just using that. I can potentially put something together for a numpy-pythia interface that relies on that, which would be nice as we wouldn't have to worry about updating python bindings.

**Comment by eduardo-rodrigues** [comment]
I've now released a version with the latest of the Pythia 8.2 series. That close to what you asked for. See https://github.com/scikit-hep/numpythia/releases/tag/1.2.0.

I will try and soon make a new minor release binding to 8.303.

**Comment by eduardo-rodrigues** [comment]
I know that Pythia now also provides bindings, though they are done with SWIG ... So you mean you can `pip install pythia`?

**Comment by eduardo-rodrigues** [comment]
Closing at this stage since there is nobody available at the moment to upgrade to Pythia 8.3, which is likely to require a lot of work. This package lacks a maintainer as said often.
