### ISSUE TITLE
Expose end vertex

### ISSUE THREAD

**Issue by jacanchaplais** [scikit-hep/numpythia#45]
Hi there,

Thanks for your work on this project.

I see that you expose the production vertex for the particles, and was just wondering whether it is possible to do the same for the end vertices. Ideally, it would be great to have the ability to extract the vertices, and their in / out particles, preferably with an id attached to them so there's no need to do any dodgy boolean comparisons against floating point structured arrays (to identify unique particles / vertices amongst duplicates).

Kind regards,
Jacan.

**Comment by eduardo-rodrigues** [comment]
Hi. Apologies for the late reply. This went unnoticed.

It is certainly possible to enhance the package. The big issue, now raised regularly in issues, is the fact that this package no longer has a maintainer and we (org admins) are only effectively able to do easy updates and maintenance, but no new developments. The latter would need a dedicated person. I'm sorry but this can happen in work that is community-driven and community-oriented. The level of interest seems to be very low these days, many likely using the Pythia bindinds directly.

**Comment by jacanchaplais** [comment]
Hi Eduardo,
No worries, I understand - thanks for your reply! :)
Kind regards,
Jacan.

**Comment by jacanchaplais** [comment]
> many likely using the Pythia bindinds directly.

Hi there, sorry for dredging up a dead issue, but just to say that I have been developing a package to act as an adaptor for Pythia's C++ Python bindings, with a Pythonic iterator and exposing data as numpy arrays. The ancestry is also available as a COO adjacency list, as well.

README and formal documentation need updates, but the docstrings are accurate.
https://github.com/jacanchaplais/showerpipe

**Comment by eduardo-rodrigues** [comment]
Thanks @jacanchaplais. From a little look I see that you have code to look at LHE files. Have you considered to contribute to https://github.com/scikit-hep/pylhe to enhance it?

**Comment by jacanchaplais** [comment]
Hi Eduardo,

I actually tried using pylhe a year or so ago, but couldn't find the functionality I needed. I'd be happy to add some features. Would I do that by forking and putting in a pull request? I was considering moving the LHE module of showerpipe to heparchy, in the end https://github.com/jacanchaplais/heparchy, but happy to offer what I have in the meantime. :)

Jacan.

**Comment by eduardo-rodrigues** [comment]
Hello Jacan,

Apologies for the very slow reply!

 It would be great if you can contribute and improve the package for the benefit of all! Pylhe has some visibility and contributions are properly acknowledged also. It would be a win-win. 

Yes, forking, etc. would be the standard way. Note that you can also open an issue if you fancy a little discussion with maintainers on some enhancement before any actual commit. That can be very handy.

Season greetings!
