### ISSUE TITLE
HepMC3 output format incompatible with pyhepmc_ng

### ISSUE THREAD

**Issue by jacanchaplais** [scikit-hep/numpythia#46]
Hi there,

I tried out writing to HepMC with this package today, and then reading back in with `pyhepmc_ng`, but ran into an issue. Although the HepMC file says it's version 3.0.0 in the header, it still appears to use the deprecated `IO_GenEvent` prefix to `START_EVENT_LISTING`, vs the newer `Asciiv3` prefix. There is some discussion of their usage here:
https://www.sciencedirect.com/science/article/pii/S0010465520301181

If I manually change the text in the header, it reads without issue.

Is this on purpose? Or would it be possible to update the header?

Kind regards,
Jacan.

**Comment by eduardo-rodrigues** [comment]
Hi, this is rather an issue for pyhepmc_ng, no? This is nothing to do with Pythia / numpythia. Closing (but reopen if I misunderstood).

**Comment by jacanchaplais** [comment]
Hi Eduardo,

Is this not to do with the fact that HepMC3 files should be using the `Asciiv3` prefix in general? I am not an expert at all, but just wanted to check in case it had been missed.

Kind regards,
Jacan.

**Comment by eduardo-rodrigues** [comment]
I'm no expert there either, actually. I think @HDembinski will know. Else the C++ HepMC authors, of course.

**Comment by jacanchaplais** [comment]
Here's that document anchored to the relevant section:
https://www.sciencedirect.com/science/article/pii/S0010465520301181#d1e2734

Following our discussion in #45 I'll probably try to use the Pythia python bindings and write straight to my hdf5 formats, so no worries if this slips beneath the radar. :)
