### ISSUE TITLE
Some documentation on pythia settings

### ISSUE THREAD

**Issue by cranmer** [scikit-hep/numpythia#5]
It's not obvious how one controls the pythia settings, selects which process, etc. Maybe I'm missing it, but I don't see that documented.

**Comment by eduardo-rodrigues** [comment]
@ndawe, any input and/or comment here?

**Comment by ndawe** [comment]
Sorry for completely missing this in my inbox! Yes, you can pass Pythia settings through the `**kwargs` of the `Pythia(..., **kwargs)` init

```
Pythia(..., Beams_eCM=13000.)
```

or as a dict:

```
Pythia(..., params={'Beams:eCM':  13000.})
```

Note _ is replaced with : if using kwargs. kwargs takes precedence over params and they both take precedence over config. You can pass a Python command file with `Pythia(config='path/to/config.cmd')`

https://github.com/scikit-hep/numpythia/blob/master/numpythia/src/_libnumpythia.pyx#L370

**Comment by eduardo-rodrigues** [comment]
Thanks a lot @ndawe !
Will any of you two create a PR with this info added to the README? Otherwise I will try and act when back from holidays.

**Comment by eduardo-rodrigues** [comment]
Closed with https://github.com/scikit-hep/numpythia/pull/11.
