### ISSUE TITLE
Should numpythia be archived?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/numpythia#74]
Similar to https://github.com/scikit-hep/pyjet/issues/81, as `numpythia` now has a notice that it is deprecated and unmaintained (thanks @eduardo-rodrigues for PR #73) shold we also archive it? My vote is yes for the same reasons as `pyjet`.

Thoughts from @eduardo-rodrigues and @henryiii?

**Comment by eduardo-rodrigues** [comment]
Hey, you read my mind. Yes, we should archive, and my several commits this year are for the fact that I would like to first make a "legacy release" with better support. Will do asap.

**Comment by eduardo-rodrigues** [comment]
BTW, what does it imply to be archived, I mean in practice for any user coming to the repository? Nothing changes as far as releases as available on PyPI.

**Comment by eduardo-rodrigues** [comment]
Forgot - one should also archive https://github.com/scikit-hep/root_numpy and https://github.com/scikit-hep/root_pandas for the same reasons. This will get us to a "cleaner situation".

**Comment by henryiii** [comment]
Just add a note to the readme before achieving. It basically just means the repo is locked and only we can unlock it - no new issues and such. And a user can see it's archived.

**Comment by henryiii** [comment]
> Forgot - one should also archive https://github.com/scikit-hep/root_numpy and https://github.com/scikit-hep/root_pandas

I believe I've asked about that before and @chrisburr said they were still in use. Not sure if that's still true, though.

**Comment by eduardo-rodrigues** [comment]
> Just add a note to the readme before achieving. It basically just means the repo is locked and only we can unlock it - no new issues and such. And a user can see it's archived.

That I did already in one of my recent PRs :-).

**Comment by matthewfeickert** [comment]
> Yes, we should archive, and my several commits this year are for the fact that I would like to first make a "legacy release" with better support. Will do asap.

Sounds good and no rush. Glad that you already had a plan here. :+1:

**Comment by eduardo-rodrigues** [comment]
Archiving.
